### ISSUE TITLE
Deploy Llama 3 70B on AWS Inferentia2: Avg. First-Time-To-Token: 5505.33ms - is it normal?

### ISSUE THREAD

**Issue by ibicdev** [philschmid/huggingface-inferentia2-samples#11]
Hi Phil, thanks for yet another great post (Deploy Llama 3 70B on AWS Inferentia2).  I saw the benchmark results have

`Avg. First-Time-To-Token: 5505.33ms`

Which seems a bit too high.  I tried to run exactly the same benchmark command as in your notebook against a vLLM endpoint on an AWS p4d instance and got similar numbers to Inferentia2, except for ttfs, which is around 100ms.  If Inferentia2 has 50X ttfs then it's almost unusable for real-time use cases.  Do you know whether this is typical for Inferentia2, or it could be a typo?

Thanks!

**Comment by philschmid** [comment]
Hey, 

Sorry if that wasn't clear. I added a big disclaimer already that this number must be taken cautiously since it includes heavy network overhead from Europe to the U.S. Inference was not run on the same machine. Additionally, for inferentia2, it depends on the number of loads, e.g., if 20 requests at the same time come in, it's pretty high. 

I recommend running your own test and then comparing.

**Comment by ibicdev** [comment]
That makes sense - thanks for the reply.
